name: RDP-With-Internet
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
      - name: Install Tailscale
        run: |
          Invoke-WebRequest -Uri https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -OutFile tailscale.exe
          Start-Process -FilePath .\tailscale.exe -ArgumentList "/S" -Wait
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey=${{ secrets.TS_KEY }} --advertise-exit-node --hostname=My-RDP-4000Mbps
      - name: Enable RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Rdp12345678" -Force)
          Write-Host "RDP Ready"
          while ($true) { Start-Sleep 300 }
